# Generated by Django 2.0.7 on 2018-07-29 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='ناشناس', max_length=50, null=True)),
                ('acc_num', models.CharField(max_length=30)),
                ('rial_wallet', models.IntegerField(default=0)),
                ('dollar_wallet', models.IntegerField(default=0)),
                ('euro_wallet', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 7, 29, 7, 41, 59, 517345, tzinfo=utc))),
                ('subject', models.CharField(default='موضوع', max_length=30)),
                ('content', models.CharField(default='محتوا', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 29, 7, 41, 59, 516697, tzinfo=utc))),
                ('type', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='در حال انتظار', max_length=30)),
                ('subject', models.CharField(default='موضوع', max_length=30)),
                ('content', models.CharField(default='محتوا', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.myuser',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dollor_account', models.CharField(default='موضوع', max_length=30)),
                ('euro_account', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.myuser',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferestande', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='girande', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignee', to='blog.Employee'),
        ),
    ]
